### ISSUE TITLE
integration_tests fail

### ISSUE THREAD

**Issue by vincentcr** [masylum/mongolia#20]
when running tests with latest mongo, integration_tests fail:

<pre>

» 12 asserts

✿ integration/integration_test.js :

Insert documents with before/afterInsert hooks => ✓ ✓ ✓ ✓ ✓ ✓ ✓ ✓

Update embedded documents =>
✗ => AssertionError: 1 ==
    at Object.equal (/cygdrive/c/Users/vincent/Documents/devel/test/node_modules/mongolia/node_modules/testosterone/lib/testosterone.js:47:39)
    at /cygdrive/c/Users/vincent/Documents/devel/test/node_modules/mongolia/test/integration/integration_test.js:83:20
    at Collection.update (/cygdrive/c/Users/vincent/Documents/devel/test/node_modules/mongodb/lib/mongodb/collection.js:370:12)
    at /cygdrive/c/Users/vincent/Documents/devel/test/node_modules/mongolia/lib/model.js:360:18
    at [object Object].collection (/cygdrive/c/Users/vincent/Documents/devel/test/node_modules/mongodb/lib/mongodb/db.js:161:14)
    at Object.getCollection (/cygdrive/c/Users/vincent/Documents/devel/test/node_modules/mongolia/lib/model.js:29:8)
    at Object.updateEmbeddedDocument (/cygdrive/c/Users/vincent/Documents/devel/test/node_modules/mongolia/lib/model.js:355:11)
    at /cygdrive/c/Users/vincent/Documents/devel/test/node_modules/mongolia/test/integration/integration_test.js:82:16
    at [object Object].<anonymous> (/cygdrive/c/Users/vincent/Documents/devel/test/node_modules/mongodb/lib/mongodb/collection.js:687:5)
    at [object Object].emit (events.js:67:17)

</pre>

**Comment by masylum** [comment]
Fixed. Thank's for reporting.

New versions of mongo don't return anything on calling `update`.
